name: Docker Image CI
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TEST: test
  DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_UNAME }}
  REGISTRYNAME: ${{ vars.REGISTRYNAME }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test Point for docker config before login
      run: |
        echo "See below uncencrypted data =>"
        cat /home/runner/.docker/config.json

    - name: Docker Hub Login
      env:
        UNAME: ${{ vars.DOCKER_HUB_UNAME }}
        PASWWD: ${{ secrets.DOCKER_HUB_PASSWD }}
      run: |
        echo "Login into the docker hub"
          docker login -u "$UNAME" -p "$PASWWD"

    - name: Test Point for docker config after login
      run: |
        echo "See below uncencrypted data =>"
        cat /home/runner/.docker/config.json
        
    - name: Build and Push Docker All Images
      uses: docker/build-push-action@v5
      with:
        push: true
        build-args: "JAR_FILE_NAME=docker-java-api-example-0.0.1"
        tags: "${DOCKER_HUB_USERNAME}/${REGISTRYNAME}:latest"

#        docker build --build-arg="JAR_FILE_NAME=docker-java-api-example-0.0.1" . -t "${DOCKER_HUB_USERNAME}/${REGISTRYNAME}" -f ./Dockerfile

    - name: List all built docker images
      run: |
        docker images | grep $DOCKER_HUB_USERNAME

    - name: Push all of docker images
      run: |
        docker-compose push
              
